#!/bin/bash
# Thanks to:
#   https://github.com/builddoctor/maven-antsy-color
#   http://blog.blindgaenger.net/colorize_maven_output.html
#   http://johannes.jakeapp.com/blog/category/fun-with-linux/200901/maven-colorized

alias maven="command mvn"
function color_maven() {
    local BLUE="[0;34m"
    local RED="[0;31m"
    local LIGHT_RED="[1;31m"
    local LIGHT_GRAY="[0;37m"
    local LIGHT_GREEN="[1;32m"
    local LIGHT_BLUE="[1;34m"
    local LIGHT_CYAN="[1;36m"
    local YELLOW="[1;33m"
    local WHITE="[1;37m"
    local NO_COLOUR="[0m"
    maven "$@" | sed \
-e "s/\(.*-\{55\}\+$\|.*\[INFO\] Scanning for projects.*\|.*\[INFO\] Building.*\|^Running .*\|^ T E S T S$\|^Results.*\)/${WHITE}\1${NO_COLOUR}/g" \
-e "s/\(.*\[INFO\] BUILD SUCCESS$\|^Tests run:.*Failures: 0.*Errors: 0.*Skipped: 0.*\)/${LIGHT_GREEN}\1${NO_COLOUR}/g" \
-e "s/\(.*\[WARNING].*\|^NOTE: Maven is executing in offline mode\.\|^Tests run:.*Failures: 0, Errors: 0, Skipped: [^0].*\)/${YELLOW}\1${NO_COLOUR}/g" \
-e "s/\(.*\[INFO\] BUILD FAILURE\|.* <<< FAILURE!$\|.* <<< ERROR!$\|^Tests in error:.*\|^Tests run:.*Failures: [^0].*\|^Tests run:.*Errors: [^0].*\|.*\[ERROR\].*\)/${LIGHT_RED}\1${NO_COLOUR}/g" \
-e "/^\[INFO\] .\{52\} /s/\( SUCCESS \)/${LIGHT_GREEN}\1${NO_COLOUR}/g" \
-e "/^\[INFO\] .\{52\} /s/\( FAILURE \)/${LIGHT_RED}\1${NO_COLOUR}/g" \
-e "/^\[INFO\] .\{52\} /s/\( SKIPPED\)/${YELLOW}\1${NO_COLOUR}/g"

    return $PIPESTATUS
}
alias mvn=color_maven

# eof
